#!/bin/sh
# postrm script for trace
set -e

case "$1" in
    purge)
        rm -rf /var/lib/trace
        deluser --quiet --system trace 2>/dev/null || true
        delgroup --quiet --system trace 2>/dev/null || true
        rm -f /etc/default/trace
        ;;
esac

#DEBHELPER#
exit 0
